packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  better-sqlite3: true
  esbuild: true
  msw: true
  prisma: true

minimumReleaseAgeExclude:
  - hasown
  - react-router
  - react-router-dom
  - tldts-core
  - zustand
