packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  better-sqlite3: true
  esbuild: true
  msw: true
  prisma: true

minimumReleaseAgeExclude:
  - hasown
  - react-router
  - react-router-dom
  - tldts-core
  - zustand
  - '@storybook/addon-a11y@10.4.2'
  - '@storybook/addon-docs@10.4.2'
  - '@storybook/builder-vite@10.4.2'
  - '@storybook/csf-plugin@10.4.2'
  - '@storybook/react-dom-shim@10.4.2'
  - '@storybook/react-vite@10.4.2'
  - '@storybook/react@10.4.2'
  - storybook@10.4.2
